Revert "US3987 remove dependencies on jquery-migrate"
This reverts commit 5878171343363468fee59059ef9a18aa5ac8ff2e.

Fixes error:

Error: Mismatched anonymous define() module: undefined
http://requirejs.org/docs/errors.html#mismatch